<?php

$featured = array(
	'ocep-courses-platform',
	'jw-platform',
	'ece-platform',
	'summits-platform',
	'sounds-true-radio',
	'journeys-platform',
);

$projects = array(

	'ocep-kpi-reporting-dashboard' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Reporting Dashboard',
		'subtitle'	=> 'Back-office web app',
		'project' 	=> 'ocep-kpi-reporting-dashboard',
		'thumb' 	=> 'ocep-kpi-reporting-dashboard.jpg',
		'date' 		=> '2019-07-27',
		'datetxt' 	=> 'July 2019',
		'desc'		=> 'Administrative analytics reporting dashboard developed for the <em>Sounds True</em> <em>Online Courses and Events</em> platform. Custom single page web app UI developed within the WordPress admin framework.',
		'tech'		=> 'PHP, JS/AJAX/jQuery, WordPress, MySQL, HTML, CSS',
	),

	'timed-event-player' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Timed Event Player',
		'subtitle'	=> 'JS video player',
		'project' 	=> 'timed-event-player',
		'thumb' 	=> 'timed-event-player.jpg',
		'date' 		=> '2019-04-13',
		'datetxt' 	=> 'April 2019',
		'desc'		=> 'Embeddable streaming media player played specific content at specific times of day. Displayed what was coming up next alongside a timer to show when it would start. After each timed-play ended the content would be made available for on-demand playback for 24 hours.',
		'tech'		=> 'JS/AJAX/jQuery, JS Date(), AWS S3, AWS CloudFront, JW Player, HTML, CSS',
	),

	'ocep-courses-migration-tool' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Courses Migration Tool',
		'subtitle'	=> 'Back-office web app',
		'project' 	=> 'ocep-courses-migration-tool',
		'thumb' 	=> 'ocep-courses-migration-tool.jpg',
		'date' 		=> '2019-01-02',
		'datetxt' 	=> 'January 2019',
		'desc'		=> '',
		'tech'		=> 'PHP, JS, WordPress, MySQL, HTML, CSS',
	),

	'ocep-courses-platform' => array(
		'has_url'	=> 'true',
		'type'		=> 'major',
		'title' 	=> 'Courses CMS',
		'subtitle'	=> 'Platform design and development',
		'project' 	=> 'ocep-courses-platform',
		'thumb' 	=> 'ocep-courses-platform.jpg',
		'date'	 	=> '2017-10-03',
		'datetxt' 	=> 'October 2017',
		'desc'		=> 'A courses and events web app product creation and management system featuring audio and video, live broadcasting, timed content access, interactive widgets and fully configurable formats and styles.',
		'tech'		=> 'PHP, JS, WordPress, REST API, MySQL, HTML, CSS, Photoshop',
	),

	'jw-platform' => array(
		'has_url'	=> 'true',
		'type'		=> 'major',
		'title' 	=> 'JW Cloud Player',
		'subtitle'	=> 'Systems and process integration',
		'project' 	=> 'jw-platform',
		'thumb' 	=> 'jw-platform.jpg',
		'date'	 	=> '2017-07-12',
		'datetxt' 	=> 'July 2017',
		'desc'		=> 'Designed and developed this fully customizable online course platform.',
		'tech'		=> '',
	),

	'evergreen-funnels' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Evergreen Funnels',
		'subtitle'	=> 'Automated sales pages',
		'project' 	=> 'evergreen-funnels',
		'thumb' 	=> 'evergreen-funnels.jpg',
		'date' 		=> '2016-09-29',
		'datetxt' 	=> 'September 2016',
		'desc'		=> '',
		'tech'		=> '',
	),

	'journeys-platform' => array(
		'has_url'	=> 'true',
		'type'		=> 'major',
		'title' 	=> 'Journeys Platform',
		'subtitle'	=> 'Audio course web apps',
		'project' 	=> 'journeys-platform',
		'thumb' 	=> 'journeys-platform.jpg',
		'date' 		=> '2016-08-08',
		'datetxt' 	=> 'August 2016',
		'desc'		=> '',
		'tech'		=> '',
	),

	'subscriptions-platform' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Subscriptions Platform',
		'subtitle'	=> 'Subscription-based web apps',
		'project' 	=> 'subscriptions-platform',
		'thumb' 	=> 'subscriptions-platform.jpg',
		'date' 		=> '2016-03-01',
		'datetxt' 	=> 'March 2016',
		'desc'		=> '',
		'tech'		=> '',
	),

	'summits-platform' => array(
		'has_url'	=> 'true',
		'type'		=> 'major',
		'title' 	=> 'Summits Platform',
		'subtitle'	=> 'Streaming media apps',
		'project' 	=> 'summits-platform',
		'thumb' 	=> 'summits-platform.jpg',
		'date' 		=> '2015-09-18',
		'datetxt' 	=> 'September 2015',
		'desc'		=> '',
		'tech'		=> '',
	),

	'poa-course' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'The Power of Awareness',
		'subtitle'	=> 'Sales funnel and course',
		'project' 	=> 'poa-course',
		'thumb' 	=> 'poa-course.jpg',
		'date' 		=> '2015-05-18',
		'datetxt' 	=> 'May 2015',
		'desc'		=> '',
		'tech'		=> '',
	),

	'magento-theme' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Magento Theme',
		'subtitle'	=> 'Responsive Magento 1 theme',
		'project' 	=> 'magento-theme',
		'thumb' 	=> 'magento-theme.jpg',
		'date' 		=> '2014-10-31',
		'datetxt' 	=> 'October 2014',
		'desc'		=> '',
		'tech'		=> '',
	),

	'weekly-wisdom' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Weekly Wisdom',
		'subtitle'	=> 'WordPress blog aggrigator for Magento',
		'project' 	=> 'weekly-wisdom',
		'thumb' 	=> 'weekly-wisdom.jpg',
		'date' 		=> '2014-08-01',
		'datetxt' 	=> 'August 2014',
		'desc'		=> '',
		'tech'		=> '',
	),

	'magento-digital-library' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Magento Digital Library',
		'subtitle'	=> 'Magento 1 account extension',
		'project' 	=> 'magento-digital-library',
		'thumb' 	=> 'magento-digital-library.jpg',
		'date' 		=> '2013-11-22',
		'datetxt' 	=> 'November 2013',
		'desc'		=> '',
		'tech'		=> '',
	),

	'course-widgets' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Course Widgets',
		'subtitle'	=> 'Courses web app extensions',
		'project' 	=> 'course-widgets',
		'thumb' 	=> 'course-widgets.jpg',
		'date' 		=> '2013-08-01',
		'datetxt' 	=> 'August 2013',
		'desc'		=> '',
		'tech'		=> '',
	),

	// 'direct-membership' => array(
	// 	'type'		=> 'major',
	// 	'title' 	=> 'Direct Membership',
	// 	'subtitle'	=> 'Magento 1 membership extension',
	// 	'project' 	=> 'direct-membership',
	// 	'thumb' 	=> 'direct-membership.jpg',
	// 	'date' 		=> '2012-08-01',
	// 	'datetxt' 	=> 'August 2012',
	// 	'desc'		=> '',
	// 	'tech'		=> '',
	// ),

	'practice-tracker' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Practice Tracker',
		'subtitle'	=> 'Courses web app extension',
		'project' 	=> 'practice-tracker',
		'thumb' 	=> 'practice-tracker.jpg',
		'date' 		=> '2012-01-01',
		'datetxt' 	=> 'January 2012',
		'desc'		=> '',
		'tech'		=> '',
	),

	'ece-platform' => array(
		'has_url'	=> 'true',
		'type'		=> 'major',
		'title' 	=> 'Email Capture Events',
		'subtitle'	=> 'Platform design and development',
		'project' 	=> 'ece-platform',
		'thumb' 	=> 'ece-platform.jpg',
		'date' 		=> '2011-09-01',
		'datetxt' 	=> 'September 2011',
		'desc'		=> '',
		'tech'		=> '',
	),

	'sounds-true-radio' => array(
		'has_url'	=> 'true',
		'type'		=> 'major',
		'title' 	=> 'Sounds True Radio',
		'subtitle'	=> 'Multichannel media player app',
		'project' 	=> 'sounds-true-radio',
		'thumb' 	=> 'sounds-true-radio.jpg',
		'date' 		=> '2011-07-01',
		'datetxt' 	=> 'July 2011',
		'desc'		=> '',
		'tech'		=> '',
	),

	'live-questions-manager' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Live Questions Manager',
		'subtitle'	=> 'Live chat and admin web app',
		'project' 	=> 'live-questions-manager',
		'thumb' 	=> 'live-questions-manager.jpg',
		'date' 		=> '2011-07-01',
		'datetxt' 	=> 'July 2011',
		'desc'		=> '',
		'tech'		=> '',
	),

	'ecom-webservice-components' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Webservice Components',
		'subtitle'	=> 'Ecommerce web services',
		'project' 	=> 'ecom-webservice-components',
		'thumb' 	=> 'ecom-webservice-components.jpg',
		'date' 		=> '2010-10-08',
		'datetxt' 	=> 'October 2010',
		'desc'		=> '',
		'tech'		=> '',
	),

	'konakart-theme-redesign' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Konakart Theme',
		'subtitle'	=> 'Ecommerce website theme',
		'project' 	=> 'konakart-theme-redesign',
		'thumb' 	=> 'konakart-theme-redesign.jpg',
		'date' 		=> '2010-07-01',
		'datetxt' 	=> 'July 2010',
		'desc'		=> '',
		'tech'		=> '',
	),

	'java-courses-platform' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Courses Platform',
		'subtitle'	=> 'Java-based course web apps',
		'project' 	=> 'java-courses-platform',
		'thumb' 	=> 'java-courses-platform.jpg',
		'date' 		=> '2010-01-01',
		'datetxt' 	=> 'January 2010',
		'desc'		=> '',
		'tech'		=> '',
	),

	'events-platform' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Events Platform',
		'subtitle'	=> 'Live event web apps',
		'project' 	=> 'events-platform',
		'thumb' 	=> 'events-platform.jpg',
		'date' 		=> '2009-10-01',
		'datetxt' 	=> 'October 2009',
		'desc'		=> '',
		'tech'		=> '',
	),

	'withinsight-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'WI Guides',
		'subtitle'	=> 'Marketing micro-sites',
		'project' 	=> 'withinsight-website',
		'thumb' 	=> 'withinsight-website.jpg',
		'date' 		=> '2009-06-01',
		'datetxt' 	=> 'June 2009',
		'desc'		=> '',
		'tech'		=> '',
	),

	'inbettersenses-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'In Better Senses',
		'subtitle'	=> 'Band website',
		'project' 	=> 'inbettersenses-website',
		'thumb' 	=> 'inbettersenses-website.jpg',
		'date' 		=> '2009-04-29',
		'datetxt' 	=> 'June 2009',
		'desc'		=> '',
		'tech'		=> '',
	),

	'konakart-theme' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'KonaKart',
		'subtitle'	=> 'Eccomerce store theme',
		'project' 	=> 'konakart-theme',
		'thumb' 	=> 'konakart-theme.jpg',
		'date' 		=> '2008-12-14',
		'datetxt' 	=> 'December 2008',
		'desc'		=> '',
		'tech'		=> '',
	),

	'eckhart-tolle-live-broadcast' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Eckhart Tolle',
		'subtitle'	=> 'Live streaming broadcast',
		'project' 	=> 'eckhart-tolle-live-broadcast',
		'thumb' 	=> 'eckhart-tolle-live-broadcast.jpg',
		'date' 		=> '2008-03-01',
		'datetxt' 	=> 'March 2008',
		'desc'		=> '',
		'tech'		=> '',
	),

	'ecom-download-store' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Downloads Store',
		'subtitle'	=> 'Custom ecom audio store',
		'project' 	=> 'ecom-download-store',
		'thumb' 	=> 'ecom-download-store.jpg',
		'date' 		=> '2007-06-01',
		'datetxt' 	=> 'June 2007',
		'desc'		=> '',
		'tech'		=> '',
	),

	'threeheadedgoat-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Three Headed Goat',
		'subtitle'	=> 'Record label website',
		'project' 	=> 'threeheadedgoat-website',
		'thumb' 	=> 'threeheadedgoat-website.jpg',
		'date' 		=> '2007-06-01',
		'datetxt' 	=> 'February 2007',
		'desc'		=> '',
		'tech'		=> '',
	),

	'bouldermacrepair-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Boulder Mac Repair',
		'subtitle'	=> 'Repair shop website',
		'project' 	=> 'bouldermacrepair-website',
		'thumb' 	=> 'bouldermacrepair-website.jpg',
		'date' 		=> '2006-05-01',
		'datetxt' 	=> 'May 2006',
		'desc'		=> '',
		'tech'		=> '',
	),

	'ladyvanexxa-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Lady Vanexxa',
		'subtitle'	=> 'Artist website',
		'project' 	=> 'ladyvanexxa-website',
		'thumb' 	=> 'ladyvanexxa-website.jpg',
		'date' 		=> '2004-05-01',
		'datetxt' 	=> 'May 2004',
		'desc'		=> '',
		'tech'		=> '',
	),

	'orhadash-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Or Hadash',
		'subtitle'	=> 'Therapist website',
		'project' 	=> 'orhadash-website',
		'thumb' 	=> 'orhadash-website.jpg',
		'date' 		=> '2004-02-03',
		'datetxt' 	=> 'February 2004',
		'desc'		=> '',
		'tech'		=> '',
	),

	'sporadik-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Sporadik',
		'subtitle'	=> 'Band website',
		'project' 	=> 'sporadik-website',
		'thumb' 	=> 'sporadik-website.jpg',
		'date' 		=> '2003-12-01',
		'datetxt' 	=> 'December 2003',
		'desc'		=> '',
		'tech'		=> '',
	),

	'shottogo-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Shot2Go',
		'subtitle'	=> 'Manufacturer website',
		'project' 	=> 'shottogo-website',
		'thumb' 	=> 'shottogo-website.jpg',
		'date' 		=> '2003-09-01',
		'datetxt' 	=> 'September 2003',
		'desc'		=> '',
		'tech'		=> '',
	),

	'danielhobby-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Daniel Watts',
		'subtitle'	=> 'Personal blog website',
		'project' 	=> 'danielhobby-website',
		'thumb' 	=> 'danielhobby-website.jpg',
		'date' 		=> '2003-08-20',
		'datetxt' 	=> 'August 2003',
		'desc'		=> '',
		'tech'		=> '',
	),

	'stevefoley-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Steven Foley',
		'subtitle'	=> 'Artist website',
		'project' 	=> 'stevefoley-website',
		'thumb' 	=> 'stevefoley-website.jpg',
		'date' 		=> '2002-11-01',
		'datetxt' 	=> 'November 2002',
		'desc'		=> '',
		'tech'		=> '',
	),

	'laurenmckenzie-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Lauren McKenzie',
		'subtitle'	=> 'Artist website',
		'project' 	=> 'laurenmckenzie-website',
		'thumb' 	=> 'laurenmckenzie-website.jpg',
		'date' 		=> '2002-10-01',
		'datetxt' 	=> 'October 2002',
		'desc'		=> '',
		'tech'		=> '',
	),

	'thehypnogogicorchestra-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'The Hypnogogoc Orchestra',
		'subtitle'	=> 'Band website',
		'project' 	=> 'thehypnogogicorchestra-website',
		'thumb' 	=> 'thehypnogogicorchestra-website.jpg',
		'date' 		=> '2002-03-01',
		'datetxt' 	=> 'March 2002',
		'desc'		=> '',
		'tech'		=> '',
	),

	'thekallistikollectif-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'The Kallisti Kollectif',
		'subtitle'	=> 'Art collective website',
		'project' 	=> 'thekallistikollectif-website',
		'thumb' 	=> 'thekallistikollectif-website.jpg',
		'date' 		=> '2001-05-01',
		'datetxt' 	=> 'May 2001',
		'desc'		=> '',
		'tech'		=> '',
	),

	'tonicwav-ads' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Tonic WAV',
		'subtitle'	=> 'Animated online ads',
		'project' 	=> 'tonicwav-ads',
		'thumb' 	=> 'tonicwav-ads.jpg',
		'date' 		=> '2001-04-01',
		'datetxt' 	=> 'April 2001',
		'desc'		=> '',
		'tech'		=> '',
	),

	'zeitgeist-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Zeitgeist',
		'subtitle'	=> 'Design firm website',
		'project' 	=> 'zeitgeist-website',
		'thumb' 	=> 'zeitgeist-website.jpg',
		'date' 		=> '2001-02-02',
		'datetxt' 	=> 'February 2001',
		'desc'		=> '',
		'tech'		=> '',
	),

	'brandjuice-website' => array(
		'has_url'	=> 'false',
		'type'		=> 'major',
		'title' 	=> 'Brandjuice',
		'subtitle'	=> 'Brand marketing website',
		'project' 	=> 'brandjuice-website',
		'thumb' 	=> 'brandjuice-website.jpg',
		'date' 		=> '2001-01-01',
		'datetxt' 	=> 'January 2001',
		'desc'		=> '',
		'tech'		=> '',
	),
);
